NDVI_threshold: 0.5
data_acquisition_date: Jun22_2020
data_export_path: !!python/object/apply:pathlib.WindowsPath
- c:\
- data
- remote_sensing
- potato
- data
- processed
- Jun22_2020
data_import_path: !!python/object/apply:pathlib.WindowsPath
- c:\
- data
- remote_sensing
- potato
- data
- raw
- Jun22_2020
ground_truth_path: !!python/object/apply:pathlib.WindowsPath
- c:\
- data
- remote_sensing
- potato
- data
- raw
- ground_truth.csv
plot_export_path: !!python/object/apply:pathlib.WindowsPath
- c:\
- data
- remote_sensing
- potato
- image_export
- Jun22_2020
project_stub: Potato_Fertilizer_Othello
